TebLocalPlannerROS:

 # Trajectory
 teb_autosize: True
 dt_ref: 0.05
 dt_hysteresis: 0.01
 global_plan_overwrite_orientation: True # follow heading of global plan
 max_global_plan_lookahead_dist: 10.0
 feasibility_check_no_poses: 5

 # Robot
 max_vel_x: 2.0
 max_vel_y: 2.0
 max_vel_x_backwards: 2.0
 max_vel_y_backwards: 2.0
 max_vel_theta: 1.5
 acc_lim_x: 2.0
 acc_lim_y: 2.0
 acc_lim_theta: 1.5
 min_turning_radius: 0.0
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "circular"
   radius: 0.60 # for type "circular"

 # GoalTolerance
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: True

 # Obstacles
 min_obstacle_dist: 0.001
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 5
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 1.0
 weight_max_vel_x: 1
 weight_max_vel_y: 1
 weight_max_vel_theta: 0.5
 weight_acc_lim_x: 1
 weight_acc_lim_y: 1
 weight_acc_lim_theta: 2
 weight_kinematics_nh: 0.2 # 0 means control for a holonomic vehicle
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 10
 weight_obstacle: 5
 weight_dynamic_obstacle: 5
 alternative_time_cost: True

 # Homotopy Class Planner
 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False